Publishers/Controllers/authorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Publishers.Models;
using PagedList;

namespace Publishers.Controllers
{
    public class authorsController : Controller
    {
        private PublishersContext db = new PublishersContext();

        //// GET: authors
        //public ActionResult Index()
        //{
        //    return View(db.authors.ToList());
        //}

        public ActionResult Index(Recherche recherche)
        {
            var lesAuteurs = db.authors.AsQueryable();
            // Les critères de recherche
            if (!string.IsNullOrWhiteSpace(recherche.nomAuteur))
            {
                if (recherche.typeRecherche == TypeRecherche.CommencePar)
                {
                    lesAuteurs = lesAuteurs.Where(n => n.au_lname.StartsWith(recherche.nomAuteur));
                }
                else
                {
                    lesAuteurs = lesAuteurs.Where(n => n.au_lname.Contains(recherche.nomAuteur));
                }
            }

            lesAuteurs = lesAuteurs.OrderBy(a => a.au_lname);

            // La pagination
            if (recherche.PageCourante == 0)
                recherche.PageCourante = 1;

            ViewBag.PageCourante = recherche.PageCourante;


            IPagedList<author> pagedList = lesAuteurs.ToPagedList(recherche.PageCourante, 10);
            ViewBag.PageCount = pagedList.PageCount;

            return View(pagedList);
        }


        // GET: authors/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            author author = db.authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: authors/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "au_id,au_lname,au_fname,phone,address,city,state,zip,contract")] author author)
        {
            if (ModelState.IsValid)
            {
                db.authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: authors/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            author author = db.authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: authors/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "au_id,au_lname,au_fname,phone,address,city,state,zip,contract")] author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: authors/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            author author = db.authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            author author = db.authors.Find(id);
            db.authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //POST: Suppression auteur ajax
        [HttpPost]
        public ActionResult SupprAuteur(string id)
        {
            string message = "L'auteur a bien été supprimé";
            if (string.IsNullOrWhiteSpace(id))
            {
                message = "Aucune clé ne correspond à l'auteur";
            }
            //Recherche de l'auteur
            author AuteurADelete = db.authors.Where(aut => aut.au_id.Equals(id)).SingleOrDefault();
            if (AuteurADelete == null)
            {
                message = "L'auteur n'existe pas, ou a déjà été supprimé";
            }
            else
            {
                try
                {
                    // Suppression du panier
                    db.authors.Remove(AuteurADelete);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    message = "L'auteur n'a pas pu être supprimé : " + ex.Message;
                    id = "0";
                }
            }

            return Json(new { DeleteId = id, Message = message });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Publishers/Controllers/titlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Publishers.Models;

namespace Publishers.Controllers
{
    public class titlesController : Controller
    {
        private PublishersContext db = new PublishersContext();

        // GET: titles
        public ActionResult Index()
        {
            var titles = db.titles.Include(t => t.publisher).Include(t => t.roysched);
            return View(titles.ToList());
        }

        // GET: titles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            title title = db.titles.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            return View(title);
        }

        // GET: titles/Create
        public ActionResult Create()
        {
            ViewBag.pub_id = new SelectList(db.publishers, "pub_id", "pub_name");
            ViewBag.title_id = new SelectList(db.royscheds, "title_id", "title_id");
            return View();
        }

        // POST: titles/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "title_id,title1,type,pub_id,price,advance,royalty,ytd_sales,notes,pubdate")] title title)
        {
            if (ModelState.IsValid)
            {
                db.titles.Add(title);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.pub_id = new SelectList(db.publishers, "pub_id", "pub_name", title.pub_id);
            ViewBag.title_id = new SelectList(db.royscheds, "title_id", "title_id", title.title_id);
            return View(title);
        }

        // GET: titles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            title title = db.titles.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            ViewBag.pub_id = new SelectList(db.publishers, "pub_id", "pub_name", title.pub_id);
            ViewBag.title_id = new SelectList(db.royscheds, "title_id", "title_id", title.title_id);
            return View(title);
        }

        // POST: titles/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "title_id,title1,type,pub_id,price,advance,royalty,ytd_sales,notes,pubdate")] title title)
        {
            if (ModelState.IsValid)
            {
                db.Entry(title).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.pub_id = new SelectList(db.publishers, "pub_id", "pub_name", title.pub_id);
            ViewBag.title_id = new SelectList(db.royscheds, "title_id", "title_id", title.title_id);
            return View(title);
        }

        // GET: titles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            title title = db.titles.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            return View(title);
        }

        // POST: titles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            title title = db.titles.Find(id);
            db.titles.Remove(title);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Publishers/Views/authors/Create.cshtml
@model Publishers.Models.author

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.au_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.au_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.au_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.au_lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.au_lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.au_lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.au_fname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.au_fname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.au_fname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contract, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.contract)
                    @Html.ValidationMessageFor(model => model.contract, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Publishers/Views/authors/Delete.cshtml
@model Publishers.Models.author

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>author</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.au_lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.au_lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.au_fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.au_fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contract)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Publishers/Views/authors/Details.cshtml
@model Publishers.Models.author

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>author</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.au_lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.au_lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.au_fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.au_fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contract)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.au_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Publishers/Views/authors/Edit.cshtml
@model Publishers.Models.author

@{
    ViewBag.Title = "Edit";
}

@* le helper qui permet de traiter la date en shortDate*@
@helper ShortDate(DateTime dateAtraiter)
{
    @dateAtraiter.ToShortDateString();
}

<h2>Modification d'un auteur</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Auteur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.au_id)

        <div class="form-group">
            @Html.LabelFor(model => model.au_lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.au_lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.au_lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.au_fname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.au_fname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.au_fname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contract, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.contract)
                    @Html.ValidationMessageFor(model => model.contract, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<h2>Liste des ouvrages(@Model.titleauthors.Count()) </h2>

<table class="table">
    <tr>
        <th>
            @Html.LabelFor(model => model.titleauthors.First().title.title1)
        </th>
        <th>
            @Html.LabelFor(model => model.titleauthors.First().title.type)
        </th>
        <th>
            @Html.LabelFor(model => model.titleauthors.First().title.pubdate)
        </th>
    </tr>

    @foreach (var item in Model.titleauthors)
    {
        <tr>
            <td>
                @Html.ActionLink(item.title.title1, "Edit", "titles", new { id = item.title_id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title.type)
            </td>
            <td>
                @ShortDate(item.title.pubdate)
            </td>
        </tr>
    }
</table>


<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Publishers/Views/authors/Index.cshtml
@model IEnumerable<Publishers.Models.author>

@{
    ViewBag.Title = "Index";


}

<h2>Liste des auteurs</h2>

<form action="" method="post" id="formRecherche">
    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Nom de l'auteur", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.TextBox("nomAuteur", "", new { htmlAttributes = new { @class = "form-control" } })
            @Html.Label("Commence par ") @Html.RadioButton("typeRecherche", 1, true)
            @Html.Label("Contient ") @Html.RadioButton("typeRecherche", 2)

            @*Gestion de la pagination*@
            <input type="hidden" name="PageCourante" id="PageCourante" value="@ViewBag.PageCourante" />
            <input type="hidden" name="PageCount" id="PageCount" value="@ViewBag.PageCount" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Recherche" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>
@using PagedList.Mvc;

@*Affichage des pages avec les boutons précédent, suivant, etc. Les boutons sont gérés par le script « liste.js »*@
@Html.PagedListPager(Model as PagedList.IPagedList, page => "#")

<div id="update-message" class="alert alert-info" style="display: none"></div>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@*Affichage des résultats*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.au_lname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.au_fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contract)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr id="@item.au_id">
            <td id="nomAut">
                @Html.DisplayFor(modelItem => item.au_lname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.au_fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.city)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.state)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.zip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.contract)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.au_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.au_id }) |
                @*@Html.ActionLink("Delete", "supprAuteur", new { id = item.au_id })*@
                <a class="btn" href="#" id="supprAuteur" name="supprAuteur" style="padding-left:2px; padding-top:4px"><i class="fa fa-trash"></i></a>
            </td>
        </tr>
    }
</table>

@* Script pour la pagination *@

@section scripts {
    <script src="/Scripts/Site/Auteurs.js" type="text/javascript"></script>
}